// Regenerates prototype/icons.js from @mdi/js — the icon set Home Assistant
// itself uses, so every glyph here has an `mdi:` equivalent in the real build.
// Usage: npm pack @mdi/js@7.4.47 && tar xzf mdi-js-7.4.47.tgz
//        node tools/build_icons.mjs path/to/package/mdi.js
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const NAMES = [
  'mdiHome', 'mdiSofa', 'mdiSilverwareForkKnife', 'mdiStove', 'mdiBedKing', 'mdiBed',
  'mdiGarage', 'mdiBedOutline', 'mdiPineTree', 'mdiShieldHome', 'mdiCctv', 'mdiFlash',
  'mdiThermometer', 'mdiLightbulb', 'mdiLightbulbOutline', 'mdiLightbulbGroup', 'mdiTelevision',
  'mdiAccountGroup', 'mdiAccount', 'mdiReceiptText', 'mdiHeartPulse', 'mdiRouterWireless',
  'mdiAlertCircle', 'mdiAlert', 'mdiWeatherCloudy', 'mdiWeatherPartlyCloudy', 'mdiWeatherRainy',
  'mdiWeatherSunny', 'mdiWeatherNight', 'mdiWaterPercent', 'mdiSolarPower', 'mdiFan',
  'mdiAirPurifier', 'mdiBlindsHorizontal', 'mdiDoorClosed', 'mdiDoorOpen', 'mdiMotionSensor',
  'mdiBellRing', 'mdiBatteryAlert', 'mdiBattery50', 'mdiCart', 'mdiChevronRight', 'mdiChevronLeft',
  'mdiTranslate', 'mdiThemeLightDark', 'mdiMovieOpen', 'mdiPower', 'mdiPowerSocketAu', 'mdiFridge',
  'mdiCoffee', 'mdiPrinter', 'mdiSpeaker', 'mdiCellphone', 'mdiTablet', 'mdiUpdate', 'mdiCloudCheck',
  'mdiWifi', 'mdiWifiOff', 'mdiAlarmLight', 'mdiPaw', 'mdiCheckCircle', 'mdiCloseCircle',
  'mdiInformationOutline', 'mdiLeaf', 'mdiCashMultiple', 'mdiCalendar', 'mdiClockOutline', 'mdiPlus',
  'mdiMinus', 'mdiPlay', 'mdiPause', 'mdiVolumeHigh', 'mdiSnowflake', 'mdiFire', 'mdiDotsHorizontal',
  'mdiRobot', 'mdiPalette', 'mdiLamp', 'mdiDatabase', 'mdiEye', 'mdiFlaskOutline', 'mdiMenu',
  'mdiClose', 'mdiArrowUp', 'mdiArrowDown', 'mdiWeatherSunsetDown', 'mdiLightbulbOff', 'mdiGauge',
  'mdiCircleOffOutline', 'mdiTune', 'mdiCog', 'mdiMapMarker', 'mdiCheck',
];

const src = fs.readFileSync(process.argv[2], 'utf8');
const out = {};
for (const n of NAMES) {
  const m = src.match(new RegExp(`export var ${n} = "([^"]+)"`));
  if (!m) throw new Error(`missing icon ${n}`);
  const key = n.slice(3).replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
  out[key] = m[1];
}
const here = path.dirname(fileURLToPath(import.meta.url));
const body = `// Generated by tools/build_icons.mjs from @mdi/js 7.4.47 (Apache-2.0). Do not edit.\n` +
  `window.CR_ICONS = ${JSON.stringify(out, null, 0).replace(/","/g, '",\n"')};\n`;
fs.writeFileSync(path.join(here, '..', 'prototype', 'icons.js'), body);
console.log(`wrote ${Object.keys(out).length} icons`);
